site_name: LeetScrape
site_url: https://leetscrape.chowkabhara.com/
docs_dir: "docs/config"
site_dir: "docs/build"
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  highlightjs: true
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - src

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

nav:
  - index.md
  - GetQuestionsList.md
  - GetQuestionInfo.md
  - GenerateCodeStub.md
  - ExctractSolutions.md
  - utils.md

extra:
  analytics:
    provider: google
    property: G-LL26YLB3M5

repo_url: https://github.com/nikhil-ravi/LeetScrape
repo_name: nikhil-ravi/LeetScrape
edit_uri: tree/main/docs/config