name: deploy-docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install poetry
        run: |
          python -m pip install poetry==1.3.2

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install --with testing,docs

      - name: Run tests
        run: |
          python -m poetry run python -m pytest tests -sxv --cov .
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Build docs
        run: |
          python -m poetry run mkdocs gh-deploy --force
